#%RAML 1.0 DataType
type: object
properties:   
  OwnerId: string
  koreps__Approval_Status__c: string
  koreps__Start_Season__c & koreps__End_Season__c: string
  koreps__Payment_Terms__c: string
  koreps__Payment_Option__c: string
  koreps__Total_Contract_Gross__c: string
  Seat__c: string
  