#%RAML 1.0 NamedExample
value:
    Company: LA Chargers
    Customer Name: Courtney
    NetSuite_ID__c: C-090000
    Customer Email: courtney.bustamante@chargers.nfl.com
    Customer Address: '3333 Susen Street Costa Mesa CA 92626'
    Customer Phone: '714-540-7100'