#%RAML 1.0 NamedExample
value:
    OwnerId: Clara Ramos
    koreps__Approval_Status__c: Deal Finalized
    koreps__Start_Season__c & koreps__End_Season__c: '2021'
    koreps__Payment_Terms__c: '30'
    koreps__Payment_Option__c: '1E-7'
    koreps__Total_Contract_Gross__c: '100000'
    Seat__c: '1E-7'
  
  